function [timesec,speedmms,normalforceN,frictionforceN,frictioncoefficient,deformationum,zstageposition] = importPODdata(filename);
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/briangraham/Desktop/TEMP/85.1 full sweep.xlsx
%    Worksheet: 85.1 full envelope
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2017/02/06 14:54:57

%% Import the data
[~, ~, raw] = xlsread(filename);
raw = raw(2:end,1:7);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));
timesec = data(:,1) - data(1,1);
speedmms = data(:,5);
normalforceN = data(:,2);
frictionforceN = data(:,3);
frictioncoefficient = data(:,7).*(speedmms > 0.5);
deformationum = -1*data(:,4);
%% Clear temporary variables
clearvars data raw R;