function [timesec,speedmms,normalforceN,frictionforceN,frictioncoefficient,deformationum] = importCSVdata(filename)
%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/briangraham/Dropbox/Solute Size Study/data/transformed/trib/clipped/b2.3.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/07/10 08:27:15

%% Initialize variables.
delimiter = ',';
startRow = 2;

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
b2 = table(dataArray{1:end-1}, 'VariableNames', {'times','speedmms','normalforceN','frictionforceN','frictioncoefficient','deformationum'});

%% Allocate imported array to column variable names
timesec = b2{:,'times'};
speedmms = b2{:,'speedmms'};
normalforceN = b2{:,'normalforceN'};
frictionforceN = b2{:,'frictionforceN'};
frictioncoefficient = b2{:,'frictioncoefficient'};
deformationum = b2{:,'deformationum'};

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;

end